const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORE={products:'dlc3.products',recent:'dlc3.recent',history:'dlc3.history',initials:'dlc3.initials',pin:'dlc3.pin'};
const MODES={production:{label:'Production',key:'daysProduction'},opening:{label:'Ouverture',key:'daysOpening'},defrost:{label:'Décongélation',key:'daysDefrost'}};
const defaultProducts=[
  {id:'pdt',name:'Purée de pommes de terre',category:'Garniture',daysProduction:'',daysOpening:'',daysDefrost:'',storage:'',favorite:true},
  {id:'jus',name:'Jus de cochon',category:'Sauce / Jus',daysProduction:'',daysOpening:'',daysDefrost:'',storage:'',favorite:false},
  {id:'arti',name:'Artichauts',category:'Légume',daysProduction:'',daysOpening:'',daysDefrost:'',storage:'',favorite:false}
];
const state={products:load(STORE.products,defaultProducts),recent:load(STORE.recent,[]),history:load(STORE.history,[]),selected:null,mode:'production',qty:1,batch:[],pinAction:null,pinActionFn:null};
function load(k,d){try{const v=JSON.parse(localStorage.getItem(k));return v??d}catch{return d}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function uid(){return (crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2))}
function todayISO(){const d=new Date(),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,10)}
function addDays(iso,n){const [y,m,d]=iso.split('-').map(Number),x=new Date(y,m-1,d);x.setDate(x.getDate()+Number(n));const z=new Date(x.getTime()-x.getTimezoneOffset()*60000);return z.toISOString().slice(0,10)}
function fmt(iso){if(!iso)return'—';const [y,m,d]=iso.split('-');return`${d}/${m}/${y}`}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),2200)}
function numOrBlank(v){if(v==='')return'';const n=Number(v);return Number.isFinite(n)&&n>=0?Math.min(365,n):''}
function ruleDays(p,mode=state.mode){return p?.[MODES[mode].key]}
function ruleSummary(p){const parts=[];if(p.daysProduction!==''&&p.daysProduction!=null)parts.push(`Prod +${p.daysProduction}j`);if(p.daysOpening!==''&&p.daysOpening!=null)parts.push(`Ouv +${p.daysOpening}j`);if(p.daysDefrost!==''&&p.daysDefrost!=null)parts.push(`Décong +${p.daysDefrost}j`);return parts.join(' · ')||'Aucune durée'}
function init(){
  if(!localStorage.getItem(STORE.products))save(STORE.products,state.products);
  $('#eventDate').value=todayISO();$('#initials').value=localStorage.getItem(STORE.initials)||'';
  bindNav();bindPrint();bindProducts();bindHistory();bindPin();bindService();renderProducts();renderQuick();renderBatch();renderHistory();updateAdminUI();updatePreview();
  if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
}
function bindNav(){$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>{$$('.nav-btn').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===b.dataset.target));window.scrollTo({top:0,behavior:'smooth'})}))}
function bindPrint(){
  $('#productSearch').addEventListener('input',showSuggestions);$('#productSearch').addEventListener('focus',showSuggestions);
  document.addEventListener('click',e=>{if(!e.target.closest('.autocomplete-wrap'))$('#suggestions').classList.add('hidden')});
  $('#modeTabs').addEventListener('click',e=>{const b=e.target.closest('button[data-mode]');if(!b)return;state.mode=b.dataset.mode;$$('#modeTabs button').forEach(x=>x.classList.toggle('active',x===b));updatePreview()});
  $('#eventDate').addEventListener('change',updatePreview);$('#lot').addEventListener('input',updatePreview);$('#initials').addEventListener('input',()=>{localStorage.setItem(STORE.initials,$('#initials').value.trim().toUpperCase());updatePreview()});
  $('#qtyMinus').addEventListener('click',()=>setQty(state.qty-1));$('#qtyPlus').addEventListener('click',()=>setQty(state.qty+1));
  $('#printNowBtn').addEventListener('click',()=>printCurrent(true));$('#addBatchBtn').addEventListener('click',addCurrentToBatch);
  $('#clearBatchBtn').addEventListener('click',()=>{if(state.batch.length&&confirm('Vider le lot préparé ?')){state.batch=[];renderBatch()}});
  $('#printBatchBtn').addEventListener('click',()=>exportBatch(true));$('#savePdfBtn').addEventListener('click',()=>exportBatch(false));
}
function showSuggestions(){const q=$('#productSearch').value.trim().toLowerCase(),list=state.products.filter(p=>!q||p.name.toLowerCase().includes(q)||(p.category||'').toLowerCase().includes(q)).slice(0,12),box=$('#suggestions');if(!list.length){box.classList.add('hidden');return}box.innerHTML=list.map(p=>`<button data-id="${p.id}"><strong>${esc(p.name)}</strong><small>${esc(p.category||'Sans catégorie')} · ${esc(ruleSummary(p))}</small></button>`).join('');box.classList.remove('hidden');box.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>selectProduct(b.dataset.id)))}
function selectProduct(id){const p=state.products.find(x=>x.id===id);if(!p)return;state.selected=p;$('#productSearch').value=p.name;$('#suggestions').classList.add('hidden');state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,8);save(STORE.recent,state.recent);renderQuick();updatePreview()}
function setQty(n){state.qty=Math.max(1,Math.min(99,n));$('#qtyValue').textContent=state.qty}
function currentItem(){const p=state.selected,days=ruleDays(p);if(!p)return{error:'Sélectionne un produit'};if(days===''||days==null)return{error:`Durée « ${MODES[state.mode].label} » non renseignée dans le PMS`};const date=$('#eventDate').value||todayISO();return{id:uid(),product:p.name,category:p.category||'',type:MODES[state.mode].label,date,days:Number(days),dlc:addDays(date,Number(days)),lot:$('#lot').value.trim(),initials:$('#initials').value.trim().toUpperCase(),storage:p.storage||'',qty:state.qty}}
function updatePreview(){const p=state.selected,days=ruleDays(p),date=$('#eventDate').value||todayISO();$('#lpProduct').textContent=p?.name||'NOM DU PRODUIT';$('#lpMode').textContent=MODES[state.mode].label.toUpperCase();$('#lpDate').textContent=fmt(date);$('#lpLot').textContent='Lot : '+($('#lot').value.trim()||'—');$('#lpInitials').textContent=$('#initials').value.trim().toUpperCase()||'—';$('#lpTemp').textContent=p?.storage||'';$('#durationValue').textContent=(days===''||days==null)?'—':days;if(p&&days!==''&&days!=null){const dlc=addDays(date,Number(days));$('#dlcValue').textContent=fmt(dlc);$('#lpDlc').textContent=fmt(dlc);$('#ruleHint').textContent=`${MODES[state.mode].label} : J+${days}`;setExpiryStatus(dlc)}else{$('#dlcValue').textContent='—';$('#lpDlc').textContent='--/--/----';$('#ruleHint').textContent=p?`Durée ${MODES[state.mode].label.toLowerCase()} à renseigner dans la base produits.`:'Sélectionne un produit.';setExpiryStatus(null)}}
function setExpiryStatus(iso){const b=$('#expiryBox');b.className='expiry-box neutral';if(!iso)return;const t=todayISO();if(iso<t)b.classList.add('danger');else if(iso===t)b.classList.add('warn');else b.classList.add('ok')}
function labelObject(x){return{product:x.product,type:x.type,date:fmt(x.date),dlc:fmt(x.dlc),lot:x.lot,initials:x.initials,storage:x.storage,dateLabel:x.type==='Ouverture'?'OUVERT LE':x.type==='Décongélation'?'DÉCONG. LE':'PROD. LE',expiryLabel:'DLC'}}
function expanded(items){const out=[];items.forEach(x=>{for(let i=0;i<x.qty;i++)out.push(labelObject(x))});return out}
async function shareOrSave(blob,name,share=true){const f=new File([blob],name,{type:'application/pdf'});if(share&&navigator.canShare?.({files:[f]})){try{await navigator.share({files:[f],title:'Étiquettes DLC 40×30',text:'PDF 40×30 prêt pour Print Master'});return true}catch(e){if(e.name==='AbortError')return false}}download(blob,name);toast('PDF enregistré');return true}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1500)}
async function printCurrent(share){const x=currentItem();if(x.error)return toast(x.error);const labels=expanded([x]);const blob=PDF40x30.make(labels);const name=`DLC_${slug(x.product)}_${todayISO()}.pdf`;const done=await shareOrSave(blob,name,share);if(done){recordHistory([x],labels.length,'PDF direct');toast(`${labels.length} étiquette${labels.length>1?'s':''} prête${labels.length>1?'s':''}`)}}
function addCurrentToBatch(){const x=currentItem();if(x.error)return toast(x.error);state.batch.push(x);renderBatch();toast(`${x.qty} étiquette${x.qty>1?'s':''} ajoutée${x.qty>1?'s':''}`)}
function renderBatch(){const total=state.batch.reduce((s,x)=>s+x.qty,0);$('#batchSummary').textContent=`${total} étiquette${total!==1?'s':''} · ${state.batch.length} produit${state.batch.length!==1?'s':''}`;$('#printBatchBtn').disabled=!total;$('#savePdfBtn').disabled=!total;const box=$('#batchList');if(!state.batch.length){box.className='stack empty-state';box.innerHTML='<p>Aucune étiquette préparée.</p>';return}box.className='stack';box.innerHTML=state.batch.map(x=>`<div class="batch-item"><div class="item-main"><div class="item-title">${esc(x.product)} · ${esc(x.type)}</div><div class="item-meta">${fmt(x.date)} → ${fmt(x.dlc)}${x.lot?' · Lot '+esc(x.lot):''}</div></div><div class="item-actions"><div class="qty-badge">×${x.qty}</div><button class="mini-btn danger" data-remove="${x.id}">✕</button></div></div>`).join('');box.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{state.batch=state.batch.filter(x=>x.id!==b.dataset.remove);renderBatch()}))}
async function exportBatch(share){if(!state.batch.length)return;const labels=expanded(state.batch);const blob=PDF40x30.make(labels);const name=`DLC_Lot_${todayISO()}_${labels.length}etq.pdf`;const done=await shareOrSave(blob,name,share);if(done){recordHistory(state.batch,labels.length,'Lot PDF');toast(`${labels.length} étiquettes prêtes`)}}
function recordHistory(items,count,kind){state.history.unshift({id:uid(),createdAt:new Date().toISOString(),count,kind,items:items.map(x=>({...x}))});state.history=state.history.slice(0,120);save(STORE.history,state.history);renderHistory()}
function slug(s){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'_').replace(/^_|_$/g,'').slice(0,35)||'Etiquette'}
function bindProducts(){$('#newProductBtn').addEventListener('click',()=>requestAdmin(()=>openProductDialog()));$('#productFilter').addEventListener('input',renderProducts);$('#productForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#productId').value||uid(),name=$('#productName').value.trim();if(!name)return;const obj={id,name,category:$('#productCategory').value.trim(),daysProduction:numOrBlank($('#daysProduction').value),daysOpening:numOrBlank($('#daysOpening').value),daysDefrost:numOrBlank($('#daysDefrost').value),storage:$('#productStorage').value.trim(),favorite:$('#productFavorite').checked};if([obj.daysProduction,obj.daysOpening,obj.daysDefrost].every(v=>v===''))return toast('Renseigne au moins une durée PMS');const i=state.products.findIndex(p=>p.id===id);if(i>=0)state.products[i]=obj;else state.products.push(obj);state.products.sort((a,b)=>a.name.localeCompare(b.name,'fr'));save(STORE.products,state.products);if(state.selected?.id===id)state.selected=obj;renderProducts();renderQuick();updatePreview();$('#productDialog').close();toast('Produit enregistré')});$('#exportProductsBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:3,exportedAt:new Date().toISOString(),products:state.products},null,2)],{type:'application/json'});download(blob,`Base_DLC_${todayISO()}.json`)});$('#importProductsInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;requestAdmin(async()=>{try{const obj=JSON.parse(await f.text());if(!Array.isArray(obj.products))throw new Error();if(!confirm(`Remplacer la base actuelle par ${obj.products.length} produit(s) ?`))return;state.products=obj.products;save(STORE.products,state.products);renderProducts();renderQuick();toast('Base importée')}catch{toast('Fichier invalide')}finally{e.target.value=''}})});$('#adminToggleBtn').addEventListener('click',()=>localStorage.getItem(STORE.pin)?requestPin('disable'):requestPin('enable'))}
function openProductDialog(p=null){$('#productDialogTitle').textContent=p?'Modifier le produit':'Nouveau produit';$('#productId').value=p?.id||'';$('#productName').value=p?.name||'';$('#productCategory').value=p?.category||'';$('#daysProduction').value=p?.daysProduction??'';$('#daysOpening').value=p?.daysOpening??'';$('#daysDefrost').value=p?.daysDefrost??'';$('#productStorage').value=p?.storage||'';$('#productFavorite').checked=!!p?.favorite;$('#productDialog').showModal();setTimeout(()=>$('#productName').focus(),60)}
function renderProducts(){const q=$('#productFilter').value.trim().toLowerCase(),list=state.products.filter(p=>!q||p.name.toLowerCase().includes(q)||(p.category||'').toLowerCase().includes(q)),box=$('#productsList');if(!list.length){box.className='stack empty-state';box.innerHTML='<p>Aucun produit.</p>';return}box.className='stack';box.innerHTML=list.map(p=>`<div class="product-item"><div class="item-main"><div class="item-title">${p.favorite?'★ ':''}${esc(p.name)}</div><div class="item-meta">${esc(p.category||'Sans catégorie')} · ${esc(ruleSummary(p))}${p.storage?' · '+esc(p.storage):''}</div></div><div class="item-actions"><button class="mini-btn" data-use="${p.id}">Utiliser</button><button class="mini-btn" data-edit="${p.id}">Modifier</button><button class="mini-btn danger" data-delete="${p.id}">✕</button></div></div>`).join('');box.querySelectorAll('[data-use]').forEach(b=>b.addEventListener('click',()=>{selectProduct(b.dataset.use);document.querySelector('[data-target="print"]').click()}));box.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>requestAdmin(()=>openProductDialog(state.products.find(p=>p.id===b.dataset.edit)))));box.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>requestAdmin(()=>{const p=state.products.find(x=>x.id===b.dataset.delete);if(p&&confirm(`Supprimer « ${p.name} » ?`)){state.products=state.products.filter(x=>x.id!==p.id);save(STORE.products,state.products);renderProducts();renderQuick()}})))}
function renderQuick(){const favorites=state.products.filter(p=>p.favorite),rec=state.recent.map(id=>state.products.find(p=>p.id===id)).filter(Boolean),seen=new Set(),list=[...favorites,...rec].filter(p=>{if(seen.has(p.id))return false;seen.add(p.id);return true}).slice(0,10),wrap=$('#quickWrap'),box=$('#quickProducts');if(!list.length){wrap.classList.add('hidden');return}wrap.classList.remove('hidden');box.innerHTML=list.map(p=>`<button class="quick-chip" data-id="${p.id}"><strong>${p.favorite?'★ ':''}${esc(p.name)}</strong><span>${esc(p.category||'')} ${p.daysProduction!==''&&p.daysProduction!=null?'· Prod +'+p.daysProduction+'j':''}</span></button>`).join('');box.querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>selectProduct(b.dataset.id)))}
function bindHistory(){$('#clearHistoryBtn').addEventListener('click',()=>{if(state.history.length&&confirm('Effacer l’historique local ?')){state.history=[];save(STORE.history,state.history);renderHistory()}});$('#exportHistoryBtn').addEventListener('click',exportHistory)}
function renderHistory(){const box=$('#historyList');if(!state.history.length){box.className='stack empty-state';box.innerHTML='<p>Aucun PDF créé.</p>';return}box.className='stack';box.innerHTML=state.history.map(h=>{const when=new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(h.createdAt)),names=(h.items||[]).slice(0,3).map(x=>`${esc(x.product)} ×${x.qty}`).join(' · ')+((h.items||[]).length>3?'…':'');return`<div class="history-item"><div class="item-main"><div class="item-title">${h.count} étiquette${h.count>1?'s':''} · ${esc(h.kind||'PDF')}</div><div class="item-meta">${when}<br>${names}</div></div><button class="mini-btn" data-reload="${h.id}">Recharger</button></div>`}).join('');box.querySelectorAll('[data-reload]').forEach(b=>b.addEventListener('click',()=>{const h=state.history.find(x=>x.id===b.dataset.reload);if(!h)return;state.batch=(h.items||[]).map(x=>({...x,id:uid()}));renderBatch();document.querySelector('[data-target="print"]').click();toast('Lot rechargé')}))}
function exportHistory(){const rows=[['Créé le','Produit','Type','Date','Durée jours','DLC','Lot','Initiales','Conservation','Quantité']];state.history.slice().reverse().forEach(h=>(h.items||[]).forEach(x=>rows.push([new Date(h.createdAt).toLocaleString('fr-FR'),x.product,x.type,fmt(x.date),x.days,fmt(x.dlc),x.lot,x.initials,x.storage,x.qty])));const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\r\n');download(new Blob([csv],{type:'text/csv;charset=utf-8'}),`Historique_DLC_${todayISO()}.csv`)}
function bindService(){$('#serviceBtn').addEventListener('click',()=>{$('#serviceInitials').value=localStorage.getItem(STORE.initials)||'';$('#serviceDialog').showModal()});$('#serviceForm').addEventListener('submit',e=>{e.preventDefault();const v=$('#serviceInitials').value.trim().toUpperCase();localStorage.setItem(STORE.initials,v);$('#initials').value=v;$('#eventDate').value=todayISO();updatePreview();$('#serviceDialog').close();toast('Service prêt')})}
function bindPin(){$('#pinForm').addEventListener('submit',e=>{e.preventDefault();const v=$('#pinInput').value.trim(),action=state.pinAction;if(action==='enable'){if(!/^\d{4,6}$/.test(v))return toast('Code de 4 à 6 chiffres');localStorage.setItem(STORE.pin,v);$('#pinDialog').close();updateAdminUI();toast('Verrou activé')}else if(action==='disable'){if(v!==localStorage.getItem(STORE.pin))return toast('Code incorrect');localStorage.removeItem(STORE.pin);$('#pinDialog').close();updateAdminUI();toast('Verrou désactivé')}else if(action==='authorize'){if(v!==localStorage.getItem(STORE.pin))return toast('Code incorrect');const fn=state.pinActionFn;state.pinActionFn=null;$('#pinDialog').close();fn?.()}})}
function requestPin(action,fn=null){state.pinAction=action;state.pinActionFn=fn;$('#pinInput').value='';$('#pinTitle').textContent=action==='enable'?'Créer le code administrateur':action==='disable'?'Désactiver le verrou':'Accès administrateur';$('#pinText').textContent=action==='enable'?'Choisis 4 à 6 chiffres pour verrouiller les règles PMS.':action==='disable'?'Entre le code actuel.':'Entre le code pour modifier les règles PMS.';$('#pinDialog').showModal();setTimeout(()=>$('#pinInput').focus(),50)}
function requestAdmin(fn){localStorage.getItem(STORE.pin)?requestPin('authorize',fn):fn()}
function updateAdminUI(){const on=!!localStorage.getItem(STORE.pin);$('#adminStatus').textContent=on?'Durées verrouillées':'Non verrouillé';$('#adminToggleBtn').textContent=on?'Désactiver':'Activer'}
window.addEventListener('DOMContentLoaded',init);
