/**
 * Étiquette Lorraine — backend de synchronisation multi-iPhone.
 * À coller dans Apps Script lié à un Google Sheet, puis déployer en application web.
 */
const SYNC_SHEET='APP_SYNC';
function setupSync(secret){if(!secret||String(secret).length<8)throw new Error('Utiliser une clé d’au moins 8 caractères.');PropertiesService.getScriptProperties().setProperty('SYNC_SECRET',String(secret));ensureSyncSheet_()}
function doGet(){return json_({ok:true,service:'Etiquette Lorraine Sync',time:new Date().toISOString()})}
function doPost(e){try{const body=JSON.parse((e&&e.postData&&e.postData.contents)||'{}'),expected=PropertiesService.getScriptProperties().getProperty('SYNC_SECRET');if(!expected)throw new Error('SYNC_SECRET non configurée. Exécuter setupSync().');if(String(body.secret||'')!==expected)return json_({ok:false,error:'Clé de synchronisation incorrecte'});if(body.action!=='sync')return json_({ok:false,error:'Action inconnue'});const lock=LockService.getScriptLock();lock.waitLock(15000);try{const merged=mergeSnapshot_(body.payload||{});logDevice_(body.deviceId||'',body.deviceName||'',new Date().toISOString());return json_({ok:true,products:merged.products,settings:merged.settings,serverTime:new Date().toISOString()})}finally{lock.releaseLock()}}catch(err){return json_({ok:false,error:String(err&&err.message||err)})}}
function ensureSyncSheet_(){const ss=SpreadsheetApp.getActiveSpreadsheet();let sh=ss.getSheetByName(SYNC_SHEET);if(!sh)sh=ss.insertSheet(SYNC_SHEET);if(sh.getLastRow()===0){sh.getRange(1,1,1,5).setValues([['TYPE','ID','UPDATED_AT','JSON','DEVICE']]);sh.setFrozenRows(1)}return sh}
function mergeSnapshot_(incoming){const sh=ensureSyncSheet_(),values=sh.getDataRange().getValues(),products={};let settings={labelFormat:{preset:'40x30',widthMm:40,heightMm:30},freezeMonths:3,sharedUpdatedAt:''};for(let i=1;i<values.length;i++){const [type,id,updatedAt,json]=values[i];if(type==='PRODUCT'&&id){try{products[id]=JSON.parse(json)}catch(_){}}else if(type==='SETTINGS'&&id==='shared'){try{settings=JSON.parse(json)}catch(_){}}}(incoming.products||[]).forEach(p=>{if(!p||!p.id)return;const cur=products[p.id];if(!cur||String(p.updatedAt||'')>String(cur.updatedAt||''))products[p.id]=p});const inSettings=incoming.settings||{};if(String(inSettings.sharedUpdatedAt||'')>String(settings.sharedUpdatedAt||''))settings=inSettings;rewriteSnapshot_(sh,Object.values(products),settings);return{products:Object.values(products),settings}}
function rewriteSnapshot_(sh,products,settings){const rows=products.map(p=>['PRODUCT',p.id,p.updatedAt||'',JSON.stringify(p),'']);rows.push(['SETTINGS','shared',settings.sharedUpdatedAt||'',JSON.stringify(settings),'']);sh.clearContents();sh.getRange(1,1,1,5).setValues([['TYPE','ID','UPDATED_AT','JSON','DEVICE']]);if(rows.length)sh.getRange(2,1,rows.length,5).setValues(rows);sh.setFrozenRows(1)}
function logDevice_(id,name,at){if(!id&&!name)return;const ss=SpreadsheetApp.getActiveSpreadsheet();let sh=ss.getSheetByName('SYNC_DEVICES');if(!sh){sh=ss.insertSheet('SYNC_DEVICES');sh.getRange(1,1,1,3).setValues([['DEVICE_ID','NAME','LAST_SEEN']]);sh.setFrozenRows(1)}const values=sh.getDataRange().getValues();let row=0;for(let i=1;i<values.length;i++){if(String(values[i][0])===String(id)){row=i+1;break}}if(row)sh.getRange(row,1,1,3).setValues([[id,name,at]]);else sh.appendRow([id,name,at])}
function json_(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON)}
