function bindProducts(){
  $('#newProductBtn').addEventListener('click',()=>requestAdmin(()=>openProductDialog()));$('#productFilter').addEventListener('input',renderProducts);
  $('#productForm').addEventListener('submit',e=>{e.preventDefault();saveProductFromForm()});
  $('#exportBackupBtn').addEventListener('click',exportFullBackup);$('#importBackupInput').addEventListener('change',importFullBackup);
  $('#adminToggleBtn').addEventListener('click',()=>localStorage.getItem(LEGACY.pin)?requestPin('disable'):requestPin('enable'));
}
function openProductDialog(p=null){$('#productDialogTitle').textContent=p?'Modifier le produit':'Nouveau produit';$('#productId').value=p?.id||'';$('#productName').value=p?.name||'';$('#productCategory').value=p?.category||'';$('#daysProduction').value=p?.daysProduction??'';$('#daysOpening').value=p?.daysOpening??'';$('#daysDefrost').value=p?.daysDefrost??'';$('#daysVacuum').value=p?.daysVacuum??'';$('#productAllergens').value=p?.allergens??'';$('#productStorage').value=p?.storage||'';$('#productFavorite').checked=!!p?.favorite;$('#productDialog').showModal();setTimeout(()=>$('#productName').focus(),60)}
async function saveProductFromForm(){const id=$('#productId').value||uid(),name=$('#productName').value.trim();if(!name)return;const old=state.products.find(p=>p.id===id)||null,obj={id,name,category:$('#productCategory').value.trim(),daysProduction:numOrBlank($('#daysProduction').value),daysOpening:numOrBlank($('#daysOpening').value),daysDefrost:numOrBlank($('#daysDefrost').value),daysVacuum:numOrBlank($('#daysVacuum').value),allergens:$('#productAllergens').value.trim(),storage:$('#productStorage').value.trim(),favorite:$('#productFavorite').checked,updatedAt:nowISO(),deleted:false};const i=state.products.findIndex(p=>p.id===id);if(i>=0)state.products[i]=obj;else state.products.push(obj);state.products.sort((a,b)=>(a.name||'').localeCompare(b.name||'','fr'));await persistKV('products',state.products);if(state.selected?.id===id)state.selected=obj;await audit(old?'Modifier produit':'Créer produit',name,old,obj);await markChanged('products',old?'Modification produit':'Création produit');renderProducts();renderQuick();updatePreview();$('#productDialog').close();toast('Produit enregistré')}
function renderProducts(){const q=$('#productFilter').value.trim().toLowerCase(),list=activeProducts().filter(p=>!q||p.name.toLowerCase().includes(q)||(p.category||'').toLowerCase().includes(q)),box=$('#productsList');if(!list.length){box.className='stack empty-state';box.innerHTML='<p>Aucun produit.</p>';return}box.className='stack';box.innerHTML=list.map(p=>`<div class="product-item"><div class="item-main"><div class="item-title">${p.favorite?'★ ':''}${esc(p.name)}</div><div class="item-meta">${esc(p.category||'Sans catégorie')} · ${esc(ruleSummary(p))}${p.storage?' · '+esc(p.storage):''}</div></div><div class="item-actions"><button class="mini-btn" data-use="${p.id}">Utiliser</button><button class="mini-btn" data-edit="${p.id}">Modifier</button><button class="mini-btn danger" data-delete="${p.id}">✕</button></div></div>`).join('');box.querySelectorAll('[data-use]').forEach(b=>b.addEventListener('click',()=>{selectProduct(b.dataset.use);document.querySelector('[data-target="print"]').click()}));box.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>requestAdmin(()=>openProductDialog(activeProducts().find(p=>p.id===b.dataset.edit)))));box.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>requestAdmin(()=>deleteProduct(b.dataset.delete))))}
async function deleteProduct(id){const p=state.products.find(x=>x.id===id);if(!p||!confirm(`Supprimer « ${p.name} » ?`))return;const before=structuredCloneSafe(p);p.deleted=true;p.updatedAt=nowISO();await persistKV('products',state.products);if(state.selected?.id===id){state.selected=null;$('#productSearch').value=''}await audit('Supprimer produit',p.name,before,p);await markChanged('products','Suppression produit');renderProducts();renderQuick();updatePreview()}
function renderQuick(){const products=activeProducts(),favorites=products.filter(p=>p.favorite),rec=state.recent.map(id=>products.find(p=>p.id===id)).filter(Boolean),seen=new Set(),list=[...favorites,...rec].filter(p=>{if(seen.has(p.id))return false;seen.add(p.id);return true}).slice(0,10),wrap=$('#quickWrap'),box=$('#quickProducts');if(!list.length){wrap.classList.add('hidden');return}wrap.classList.remove('hidden');box.innerHTML=list.map(p=>`<button class="quick-chip" data-id="${p.id}"><strong>${p.favorite?'★ ':''}${esc(p.name)}</strong><span>${esc(p.category||'')} · Cong ${state.settings.freezeMonths}m</span></button>`).join('');box.querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>selectProduct(b.dataset.id)))}
function exportFullBackup(){const payload={version:4,exportedAt:nowISO(),products:state.products,recent:state.recent,history:state.history,settings:sanitisedSettingsForBackup(),audit:state.audit};download(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),`Etiquette_Lorraine_Sauvegarde_${todayISO()}.json`)}
async function importFullBackup(e){const f=e.target.files?.[0];if(!f)return;requestAdmin(async()=>{try{const obj=JSON.parse(await f.text());if(!Array.isArray(obj.products))throw new Error('Produits absents');if(!confirm(`Restaurer ${obj.products.filter(p=>!p.deleted).length} produit(s) et remplacer les données locales ?`))return;state.products=obj.products.map(p=>({...p,updatedAt:p.updatedAt||nowISO(),deleted:!!p.deleted}));state.recent=Array.isArray(obj.recent)?obj.recent:[];state.history=Array.isArray(obj.history)?obj.history:[];if(obj.settings)state.settings={...state.settings,...obj.settings,labelFormat:{...state.settings.labelFormat,...(obj.settings.labelFormat||{})},sync:{...state.settings.sync,...(obj.settings.sync||{})}};await persistKV('products',state.products);await persistKV('recent',state.recent);await persistKV('history',state.history);await persistKV('settings',state.settings);await audit('Restaurer sauvegarde','Base complète',null,{products:state.products.length});await markChanged('restore','Restauration sauvegarde');renderProducts();renderQuick();renderHistory();renderSettings();updatePreview();toast('Sauvegarde restaurée')}catch(err){console.error(err);toast('Fichier de sauvegarde invalide')}finally{e.target.value=''}})}
function bindHistory(){$('#clearHistoryBtn').addEventListener('click',async()=>{if(state.history.length&&confirm('Effacer l’historique local ?')){state.history=[];await persistKV('history',state.history);await audit('Effacer historique','Historique');renderHistory()}});$('#exportHistoryBtn').addEventListener('click',exportHistory)}
function renderHistory(){const box=$('#historyList');if(!state.history.length){box.className='stack empty-state';box.innerHTML='<p>Aucun PDF créé.</p>';return}box.className='stack';box.innerHTML=state.history.map(h=>{const when=new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(h.createdAt)),names=(h.items||[]).slice(0,3).map(x=>`${esc(x.product)} ×${x.qty}`).join(' · ')+((h.items||[]).length>3?'…':''),f=h.format?`${h.format.widthMm}×${h.format.heightMm}`:'';return`<div class="history-item"><div class="item-main"><div class="item-title">${h.count} étiquette${h.count>1?'s':''} · ${esc(h.kind||'PDF')} ${f?'· '+f+' mm':''}</div><div class="item-meta">${when}<br>${names}</div></div><button class="mini-btn" data-reload="${h.id}">Recharger</button></div>`}).join('');box.querySelectorAll('[data-reload]').forEach(b=>b.addEventListener('click',()=>{const h=state.history.find(x=>x.id===b.dataset.reload);if(!h)return;state.batch=(h.items||[]).map(x=>({...x,id:uid()}));renderBatch();document.querySelector('[data-target="print"]').click();toast('Lot rechargé')}))}
function exportHistory(){const rows=[['Créé le','Produit','Type','Date','Durée','DLC/Limite','Lot','Initiales','Conservation','Quantité','Format']];state.history.slice().reverse().forEach(h=>(h.items||[]).forEach(x=>rows.push([new Date(h.createdAt).toLocaleString('fr-FR'),x.product,x.type,fmt(x.date),x.days,fmt(x.dlc),x.lot,x.initials,x.storage,x.qty,h.format?`${h.format.widthMm}x${h.format.heightMm}`:''])));const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\r\n');download(new Blob([csv],{type:'text/csv;charset=utf-8'}),`Historique_DLC_${todayISO()}.csv`)}
function bindService(){$('#serviceBtn').addEventListener('click',()=>{$('#serviceInitials').value=localStorage.getItem(LEGACY.initials)||'';$('#serviceDialog').showModal()});$('#serviceForm').addEventListener('submit',e=>{e.preventDefault();const v=$('#serviceInitials').value.trim().toUpperCase();localStorage.setItem(LEGACY.initials,v);$('#initials').value=v;$('#eventDate').value=todayISO();updatePreview();$('#serviceDialog').close();toast('Service prêt')})}
function bindPin(){$('#pinForm').addEventListener('submit',e=>{e.preventDefault();const v=$('#pinInput').value.trim(),action=state.pinAction;if(action==='enable'){if(!/^\d{4,6}$/.test(v))return toast('Code de 4 à 6 chiffres');localStorage.setItem(LEGACY.pin,v);$('#pinDialog').close();updateAdminUI();audit('Activer verrou PMS','Sécurité');toast('Verrou activé')}else if(action==='disable'){if(v!==localStorage.getItem(LEGACY.pin))return toast('Code incorrect');localStorage.removeItem(LEGACY.pin);state.settings.serviceLocked=false;persistKV('settings',state.settings).catch(()=>{});$('#pinDialog').close();updateAdminUI();renderSettings();audit('Désactiver verrou PMS','Sécurité');toast('Verrou désactivé')}else if(action==='authorize'){if(v!==localStorage.getItem(LEGACY.pin))return toast('Code incorrect');const fn=state.pinActionFn;state.pinActionFn=null;$('#pinDialog').close();Promise.resolve(fn?.()).catch(console.error)}})}
function requestPin(action,fn=null){state.pinAction=action;state.pinActionFn=fn;$('#pinInput').value='';$('#pinTitle').textContent=action==='enable'?'Créer le code administrateur':action==='disable'?'Désactiver le verrou':'Accès administrateur';$('#pinText').textContent=action==='enable'?'Choisis 4 à 6 chiffres pour protéger les règles PMS.':action==='disable'?'Entre le code actuel.':'Entre le code pour modifier les règles PMS.';$('#pinDialog').showModal();setTimeout(()=>$('#pinInput').focus(),50)}
function requestAdmin(fn){const pin=localStorage.getItem(LEGACY.pin);if(pin)requestPin('authorize',fn);else if(state.settings.serviceLocked){toast('Crée d’abord un code administrateur');requestPin('enable')}else Promise.resolve(fn()).catch(console.error)}
function updateAdminUI(){const on=!!localStorage.getItem(LEGACY.pin);$('#adminStatus').textContent=on?(state.settings.serviceLocked?'Verrouillé en service':'Code administrateur actif'):'Non verrouillé';$('#adminToggleBtn').textContent=on?'Désactiver':'Activer'}
