function bindNav(){$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>{$$('.nav-btn').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===b.dataset.target));window.scrollTo({top:0,behavior:'smooth'});if(b.dataset.target==='settings')renderSettings()}))}
function bindDialogs(){$$('[data-close]').forEach(b=>b.addEventListener('click',()=>{document.activeElement?.blur();const d=b.closest('dialog');requestAnimationFrame(()=>d?.open&&d.close('cancel'))}))}
function bindPrint(){
  $('#productSearch').addEventListener('input',showSuggestions);$('#productSearch').addEventListener('focus',showSuggestions);
  document.addEventListener('click',e=>{if(!e.target.closest('.autocomplete-wrap'))$('#suggestions').classList.add('hidden')});
  $('#modeTabs').addEventListener('click',e=>{const b=e.target.closest('button[data-mode]');if(!b)return;state.mode=b.dataset.mode;$$('#modeTabs button').forEach(x=>x.classList.toggle('active',x===b));updatePreview()});
  $('#eventDate').addEventListener('change',updatePreview);$('#lot').addEventListener('input',updatePreview);$('#initials').addEventListener('input',()=>{localStorage.setItem(LEGACY.initials,$('#initials').value.trim().toUpperCase());updatePreview()});
  $('#qtyMinus').addEventListener('click',()=>setQty(state.qty-1));$('#qtyPlus').addEventListener('click',()=>setQty(state.qty+1));
  $('#printNowBtn').addEventListener('click',()=>printCurrent(true));$('#saveCurrentBtn').addEventListener('click',()=>printCurrent(false));$('#addBatchBtn').addEventListener('click',addCurrentToBatch);
  $('#clearBatchBtn').addEventListener('click',()=>{if(state.batch.length&&confirm('Vider le lot préparé ?')){state.batch=[];renderBatch()}});
  $('#printBatchBtn').addEventListener('click',()=>exportBatch(true));$('#savePdfBtn').addEventListener('click',()=>exportBatch(false));
}
function showSuggestions(){const q=$('#productSearch').value.trim().toLowerCase(),list=activeProducts().filter(p=>!q||p.name.toLowerCase().includes(q)||(p.category||'').toLowerCase().includes(q)).slice(0,14),box=$('#suggestions');if(!list.length){box.classList.add('hidden');return}box.innerHTML=list.map(p=>`<button data-id="${p.id}"><strong>${esc(p.name)}</strong><small>${esc(p.category||'Sans catégorie')} · ${esc(ruleSummary(p))}</small></button>`).join('');box.classList.remove('hidden');box.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>selectProduct(b.dataset.id)))}
async function selectProduct(id){const p=activeProducts().find(x=>x.id===id);if(!p)return;state.selected=p;$('#productSearch').value=p.name;$('#suggestions').classList.add('hidden');state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,10);await persistKV('recent',state.recent);renderQuick();updatePreview()}
function setQty(n){state.qty=Math.max(1,Math.min(99,n));$('#qtyValue').textContent=state.qty}
function ruleDays(p,mode=state.mode){if(mode==='freeze'||mode==='allergens')return null;return p?.[MODES[mode].key]}
function ruleSummary(p){const parts=[];if(p.daysProduction!==''&&p.daysProduction!=null)parts.push(`Prod +${p.daysProduction}j`);if(p.daysOpening!==''&&p.daysOpening!=null)parts.push(`Ouv +${p.daysOpening}j`);if(p.daysDefrost!==''&&p.daysDefrost!=null)parts.push(`Décong +${p.daysDefrost}j`);if(p.daysVacuum!==''&&p.daysVacuum!=null)parts.push(`S/V +${p.daysVacuum}j`);if(p.allergens)parts.push('Allergènes');parts.push(`Cong ${state.settings.freezeMonths} mois`);return parts.join(' · ')}
function currentItem(){const p=state.selected;if(!p)return{error:'Sélectionne un produit'};const date=$('#eventDate').value||todayISO();let dlc,days,detail='',type=MODES[state.mode].label;if(state.mode==='freeze'){days=`${state.settings.freezeMonths} mois`;dlc=addMonths(date,state.settings.freezeMonths)}else if(state.mode==='allergens'){days='information';dlc=date;detail=(p.allergens||'').trim();if(!detail)return{error:'Allergènes non renseignés pour ce produit'}}else{days=ruleDays(p);if(days===''||days==null)return{error:`Durée « ${type} » non renseignée dans le PMS`};days=Number(days);dlc=addDays(date,days)}return{id:uid(),product:p.name,productId:p.id,category:p.category||'',type,date,days,dlc,detail,lot:$('#lot').value.trim(),initials:$('#initials').value.trim().toUpperCase(),storage:state.mode==='freeze'?(p.freezeStorage||'Conservation congelée'):(p.storage||''),qty:state.qty,format:structuredCloneSafe(state.settings.labelFormat)}}
function updatePreview(){const p=state.selected,date=$('#eventDate').value||todayISO(),mode=MODES[state.mode],format=state.settings.labelFormat;$('#lpProduct').textContent=p?.name||'NOM DU PRODUIT';$('#lpMode').textContent=mode.label.toUpperCase();$('#lpDate').textContent=fmt(date);$('#lpLot').textContent='Lot : '+($('#lot').value.trim()||'—');$('#lpInitials').textContent=$('#initials').value.trim().toUpperCase()||'—';$('#lpTemp').textContent=state.mode==='freeze'?(p?.freezeStorage||'Conservation congelée'):(p?.storage||'');$('#lpDateLabel').textContent=mode.dateLabel;$('#lpExpiryLabel').textContent=mode.expiryLabel;$('#expiryLabel').textContent=state.mode==='freeze'?'Limite congélation':state.mode==='allergens'?'Information allergènes':'DLC / limite';let dlc=null;if(state.mode==='freeze'){$('#durationValue').textContent=state.settings.freezeMonths;$('#durationUnit').textContent='mois';dlc=addMonths(date,state.settings.freezeMonths);$('#ruleHint').textContent=`Congélation : +${state.settings.freezeMonths} mois calendaires · règle PMS`;$('#dlcValue').textContent=fmt(dlc);$('#lpDlc').textContent=fmt(dlc)}else if(state.mode==='allergens'){$('#durationValue').textContent='INFO';$('#durationUnit').textContent='';const info=(p?.allergens||'').trim();$('#ruleHint').textContent=info?'Allergènes renseignés dans la fiche produit':'Allergènes à renseigner dans la fiche produit';$('#dlcValue').textContent=info||'—';$('#lpDlc').textContent=info||'—'}else{const days=ruleDays(p);$('#durationValue').textContent=(days===''||days==null)?'—':days;$('#durationUnit').textContent='jour(s)';if(p&&days!==''&&days!=null){dlc=addDays(date,Number(days));$('#ruleHint').textContent=`${mode.label} : J+${days}`}else $('#ruleHint').textContent=p?`Durée ${mode.label.toLowerCase()} à renseigner dans le PMS.`:'Sélectionne un produit.';$('#dlcValue').textContent=dlc?fmt(dlc):'—';$('#lpDlc').textContent=dlc?fmt(dlc):'--/--/----'}setExpiryStatus(state.mode==='allergens'?null:dlc);applyPreviewFormat(format)}
function setExpiryStatus(iso){const b=$('#expiryBox');b.className='expiry-box neutral';if(!iso)return;const t=todayISO();if(iso<t)b.classList.add('danger');else if(iso===t)b.classList.add('warn');else b.classList.add('ok')}
function applyPreviewFormat(f){const w=Number(f.widthMm)||40,h=Number(f.heightMm)||30;$('#labelPreview').style.aspectRatio=`${w}/${h}`;$('#formatChip').textContent=`Format PDF : ${w} × ${h} mm`;$('#formatEyebrow').textContent=`ÉTIQUETTES ${w} × ${h} MM`}
function labelObject(x){const mode=Object.values(MODES).find(m=>m.label===x.type)||MODES.production;return{product:x.product,type:x.type,date:fmt(x.date),dlc:x.type==='Allergènes'?'':fmt(x.dlc),detail:x.detail||'',lot:x.lot,initials:x.initials,storage:x.storage,dateLabel:mode.dateLabel,expiryLabel:mode.expiryLabel}}
function expanded(items){const out=[];items.forEach(x=>{for(let i=0;i<x.qty;i++)out.push(labelObject(x))});return out}
function pdfFormat(){return{widthMm:Number(state.settings.labelFormat.widthMm)||40,heightMm:Number(state.settings.labelFormat.heightMm)||30}}
async function shareOrSave(blob,name,share=true){const f=new File([blob],name,{type:'application/pdf'}),fmt=pdfFormat();if(share&&navigator.canShare?.({files:[f]})){try{await navigator.share({files:[f],title:`Étiquettes ${fmt.widthMm}×${fmt.heightMm}`,text:'PDF prêt pour Print Master'});return true}catch(e){if(e.name==='AbortError')return false}}download(blob,name);toast('PDF enregistré');return true}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1800)}
async function printCurrent(share){const x=currentItem();if(x.error)return toast(x.error);try{const labels=expanded([x]),fmt=pdfFormat(),blob=PDFLabels.make(labels,fmt),name=`DLC_${slug(x.product)}_${fmt.widthMm}x${fmt.heightMm}_${todayISO()}.pdf`;const done=await shareOrSave(blob,name,share);if(done){await recordHistory([x],labels.length,'PDF direct');toast(`${labels.length} étiquette${labels.length>1?'s':''} prête${labels.length>1?'s':''}`)}}catch(e){console.error(e);toast('Erreur de génération PDF')}}
function addCurrentToBatch(){const x=currentItem();if(x.error)return toast(x.error);state.batch.push(x);renderBatch();toast(`${x.qty} étiquette${x.qty>1?'s':''} ajoutée${x.qty>1?'s':''}`)}
function renderBatch(){const total=state.batch.reduce((s,x)=>s+x.qty,0);$('#batchSummary').textContent=`${total} étiquette${total!==1?'s':''} · ${state.batch.length} produit${state.batch.length!==1?'s':''}`;$('#printBatchBtn').disabled=!total;$('#savePdfBtn').disabled=!total;const box=$('#batchList');if(!state.batch.length){box.className='stack empty-state';box.innerHTML='<p>Aucune étiquette préparée.</p>';return}box.className='stack';box.innerHTML=state.batch.map(x=>`<div class="batch-item"><div class="item-main"><div class="item-title">${esc(x.product)} · ${esc(x.type)}</div><div class="item-meta">${fmt(x.date)} → ${fmt(x.dlc)}${x.lot?' · Lot '+esc(x.lot):''}</div></div><div class="item-actions"><div class="qty-badge">×${x.qty}</div><button class="mini-btn danger" data-remove="${x.id}">✕</button></div></div>`).join('');box.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{state.batch=state.batch.filter(x=>x.id!==b.dataset.remove);renderBatch()}))}
async function exportBatch(share){if(!state.batch.length)return;try{const labels=expanded(state.batch),fmt=pdfFormat(),blob=PDFLabels.make(labels,fmt),name=`DLC_Lot_${fmt.widthMm}x${fmt.heightMm}_${todayISO()}_${labels.length}etq.pdf`;const done=await shareOrSave(blob,name,share);if(done){await recordHistory(state.batch,labels.length,'Lot PDF');toast(`${labels.length} étiquettes prêtes`)}}catch(e){console.error(e);toast('Erreur de génération PDF')}}
async function recordHistory(items,count,kind){state.history.unshift({id:uid(),createdAt:nowISO(),count,kind,format:pdfFormat(),items:items.map(x=>({...x}))});state.history=state.history.slice(0,180);await persistKV('history',state.history);renderHistory()}
