function bindSettings(){
  $('#formatPreset').addEventListener('change',onPresetChange);$('#saveFormatBtn').addEventListener('click',saveFormatSettings);
  $('#savePmsSettingsBtn').addEventListener('click',()=>requestAdmin(savePmsSettings));$('#serviceLockBtn').addEventListener('click',toggleServiceLock);
  $('#runDiagnosticBtn').addEventListener('click',runDiagnostic);$('#saveSyncBtn').addEventListener('click',saveSyncSettings);$('#syncNowBtn').addEventListener('click',()=>syncNow(false));$('#checkUpdateBtn').addEventListener('click',checkForUpdate);$('#applyUpdateBtn').addEventListener('click',applyWaitingUpdate);
  window.addEventListener('online',()=>{updateConnection();if(state.settings.sync?.enabled)syncNow(true).catch(()=>{})});window.addEventListener('offline',updateConnection);document.addEventListener('visibilitychange',()=>{if(!document.hidden)updateConnection()});
}
function renderSettings(){const f=state.settings.labelFormat||defaultSettings.labelFormat;$('#formatPreset').value=f.preset||presetFromSize(f.widthMm,f.heightMm);$('#labelWidth').value=f.widthMm;$('#labelHeight').value=f.heightMm;$('#freezeMonths').value=state.settings.freezeMonths||3;$('#serviceLockBtn').textContent=state.settings.serviceLocked?'Désactiver le verrou service':'Activer le verrou service';$('#syncEnabled').checked=!!state.settings.sync?.enabled;$('#syncUrl').value=state.settings.sync?.url||'';$('#syncSecret').value=state.settings.sync?.secret||'';$('#deviceName').value=state.settings.sync?.deviceName||'';$('#syncStatus').textContent=state.settings.lastSync?`Dernière synchronisation : ${new Date(state.settings.lastSync).toLocaleString('fr-FR')}`:'Synchronisation non configurée.';$('#updateStatus').textContent=`Version locale ${APP_VERSION}`;renderBackupStatus();renderAudit();updateAdminUI()}
function presetFromSize(w,h){const key=`${Number(w)}x${Number(h)}`;return['40x30','50x30','50x40','60x40'].includes(key)?key:'custom'}
function onPresetChange(){const v=$('#formatPreset').value;if(v==='custom')return;const [w,h]=v.split('x').map(Number);$('#labelWidth').value=w;$('#labelHeight').value=h}
async function saveFormatSettings(){const w=Math.max(20,Math.min(100,Number($('#labelWidth').value)||40)),h=Math.max(20,Math.min(100,Number($('#labelHeight').value)||30)),before=structuredCloneSafe(state.settings.labelFormat),preset=presetFromSize(w,h);state.settings.labelFormat={preset,widthMm:w,heightMm:h};state.settings.sharedUpdatedAt=nowISO();await persistKV('settings',state.settings);await audit('Changer format étiquette',`${w}×${h} mm`,before,state.settings.labelFormat);await markChanged('settings','Changement format');renderSettings();updatePreview();toast(`Format ${w} × ${h} mm appliqué`)}
async function savePmsSettings(){const m=Math.max(1,Math.min(12,Number($('#freezeMonths').value)||3)),before=state.settings.freezeMonths;state.settings.freezeMonths=m;state.settings.sharedUpdatedAt=nowISO();await persistKV('settings',state.settings);await audit('Modifier règle congélation','PMS',before,m);await markChanged('settings','Réglage PMS');renderQuick();updatePreview();toast(`Congélation réglée à ${m} mois`)}
function toggleServiceLock(){if(!state.settings.serviceLocked&&!localStorage.getItem(LEGACY.pin)){toast('Crée un code administrateur pour activer le mode service');requestPin('enable');return}requestAdmin(async()=>{const before=state.settings.serviceLocked;state.settings.serviceLocked=!before;await persistKV('settings',state.settings);await audit(state.settings.serviceLocked?'Activer mode service':'Désactiver mode service','Sécurité',before,state.settings.serviceLocked);renderSettings();toast(state.settings.serviceLocked?'Mode service verrouillé':'Mode service déverrouillé')})}
function renderBackupStatus(){if(!$('#lastBackupText'))return;$('#lastBackupText').textContent=state.settings.lastBackup?`Sauvegarde interne : ${new Date(state.settings.lastBackup).toLocaleString('fr-FR')}`:'Sauvegarde interne : —'}
function renderAudit(){const box=$('#auditList');if(!box)return;if(!state.audit.length){box.className='audit-list empty-state';box.innerHTML='<p>Aucune modification enregistrée.</p>';return}box.className='audit-list';box.innerHTML=state.audit.slice(0,50).map(a=>`<div class="audit-row"><strong>${esc(a.action)} · ${esc(a.entity||'')}</strong><small>${new Date(a.createdAt).toLocaleString('fr-FR')} · ${esc(a.actor||'—')}</small></div>`).join('')}
function updateConnection(){const strip=$('#networkStrip');if(!strip)return;strip.classList.remove('online','offline','preparing');if(navigator.onLine){strip.classList.add('online');strip.querySelector('strong').textContent='En ligne';strip.querySelector('span:last-child').textContent='Application locale prête · synchronisation possible'}else{strip.classList.add('offline');strip.querySelector('strong').textContent='Mode hors ligne';strip.querySelector('span:last-child').textContent='Produits, calculs et PDF disponibles localement'}}
async function registerServiceWorker(){if(!('serviceWorker'in navigator)){updateConnection();return}try{const reg=await navigator.serviceWorker.register('./sw.js');state.registration=reg;if(reg.waiting)showUpdateBanner();reg.addEventListener('updatefound',()=>{const worker=reg.installing;if(!worker)return;worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)showUpdateBanner()})});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload());await navigator.serviceWorker.ready;updateConnection()}catch(e){console.error(e);toast('Mode hors ligne incomplet')}}
function showUpdateBanner(){$('#updateBanner').classList.remove('hidden');$('#updateStatus').textContent='Nouvelle version prête à installer'}
function applyWaitingUpdate(){const w=state.registration?.waiting;if(w)w.postMessage({type:'SKIP_WAITING'});else toast('Aucune mise à jour en attente')}
async function checkForUpdate(){if(!state.registration)return toast('Service hors ligne non disponible');$('#updateStatus').textContent='Vérification…';try{await state.registration.update();if(state.registration.waiting)showUpdateBanner();else{$('#updateStatus').textContent=`Version ${APP_VERSION} · à jour`;toast('Application à jour')}}catch(e){$('#updateStatus').textContent='Vérification impossible hors ligne';toast('Vérification impossible sans Internet')}}
async function swDiagnostic(){if(!navigator.serviceWorker?.controller)return{ok:false,missing:['service worker non contrôlant']};return new Promise(resolve=>{const ch=new MessageChannel(),timer=setTimeout(()=>resolve({ok:false,missing:['réponse service worker absente']}),2500);ch.port1.onmessage=e=>{clearTimeout(timer);resolve(e.data||{ok:false})};navigator.serviceWorker.controller.postMessage({type:'DIAGNOSE'},[ch.port2])})}
async function runDiagnostic(){const box=$('#diagnosticList');box.innerHTML='<div class="diag pending"><span>●</span><strong>Diagnostic en cours…</strong></div>';const results=[];try{if(!state.db)throw new Error();await idbPut('kv',{at:nowISO()},'diagnostic');await idbDelete('kv','diagnostic');results.push(['ok','Base IndexedDB','Lecture / écriture OK'])}catch(_){results.push(['bad','Base IndexedDB','Échec du stockage avancé'])}try{const b=PDFLabels.make([{product:'TEST',type:'Production',date:'01/01/2026',dlc:'02/01/2026',lot:'',initials:'DT',storage:'',dateLabel:'PROD. LE',expiryLabel:'DLC'}],pdfFormat());results.push([b.size>100?'ok':'bad','Générateur PDF',b.size>100?'PDF local OK':'PDF invalide'])}catch(_){results.push(['bad','Générateur PDF','Erreur de génération'])}const sw=await swDiagnostic();results.push([sw.ok?'ok':'bad','Cache hors ligne',sw.ok?'Tous les fichiers essentiels sont présents':`Manquants : ${(sw.missing||[]).join(', ')}`]);results.push([activeProducts().length?'ok':'warn','Base produits',`${activeProducts().length} produit(s) disponible(s)`]);results.push(['ok','Format étiquette',`${pdfFormat().widthMm} × ${pdfFormat().heightMm} mm`]);results.push([navigator.onLine?'ok':'warn','Connexion',navigator.onLine?'En ligne':'Hors ligne — test local actif']);box.innerHTML=results.map(([cl,t,d])=>`<div class="diag ${cl}"><span>●</span><div><strong>${esc(t)}</strong><small class="muted-line">${esc(d)}</small></div></div>`).join('');toast(sw.ok?'Mode hors ligne prêt':'Diagnostic : un point est à corriger')}
function syncPayload(){return{products:state.products,settings:{labelFormat:state.settings.labelFormat,freezeMonths:state.settings.freezeMonths,sharedUpdatedAt:state.settings.sharedUpdatedAt},updatedAt:nowISO()}}
function mergeProducts(local,remote){const map=new Map();[...local,...(remote||[])].forEach(p=>{if(!p?.id)return;const prev=map.get(p.id);if(!prev||String(p.updatedAt||'')>String(prev.updatedAt||''))map.set(p.id,p)});return[...map.values()]}
async function saveSyncSettings(){const before={...state.settings.sync,secret:state.settings.sync.secret?'***':''};state.settings.sync={enabled:$('#syncEnabled').checked,url:$('#syncUrl').value.trim(),secret:$('#syncSecret').value.trim(),deviceName:$('#deviceName').value.trim()};await persistKV('settings',state.settings);await audit('Configurer synchronisation','Multi-iPhone',before,{...state.settings.sync,secret:state.settings.sync.secret?'***':''});renderSettings();toast('Synchronisation enregistrée');if(state.settings.sync.enabled&&navigator.onLine)syncNow(true).catch(()=>{})}
async function syncNow(silent=false){const cfg=state.settings.sync;if(!cfg?.enabled||!cfg.url){if(!silent)toast('Configure d’abord la synchronisation');return false}if(!navigator.onLine){if(!silent)toast('Synchronisation mise en attente : hors ligne');return false}if(!silent)$('#syncStatus').textContent='Synchronisation…';try{const res=await fetch(cfg.url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'sync',secret:cfg.secret,deviceId:state.settings.deviceId,deviceName:cfg.deviceName,payload:syncPayload()})});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();if(!data.ok)throw new Error(data.error||'Réponse serveur invalide');if(Array.isArray(data.products)){state.products=mergeProducts(state.products,data.products);await persistKV('products',state.products)}if(data.settings){const r=data.settings,l=state.settings;if(String(r.sharedUpdatedAt||'')>String(l.sharedUpdatedAt||'')){l.labelFormat={...l.labelFormat,...(r.labelFormat||{})};l.freezeMonths=Number(r.freezeMonths)||l.freezeMonths;l.sharedUpdatedAt=r.sharedUpdatedAt;await persistKV('settings',l)}}state.settings.lastSync=nowISO();await persistKV('settings',state.settings);const out=await idbAll('outbox');for(const row of out)await idbDelete('outbox',row.id);renderProducts();renderQuick();renderSettings();updatePreview();if(!silent)toast('Synchronisation terminée');return true}catch(e){console.error(e);$('#syncStatus').textContent='Synchronisation impossible · données conservées localement';if(!silent)toast('Échec sync : données gardées hors ligne');return false}}
